name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  macos:
    runs-on: macOS-10.15
    env:
      STAGING_DIRECTORY: $(Build.StagingDirectory)
      ESY__CACHE_INSTALL_PATH: /Users/runner/.esy/3__________________________________________________________________/i
      ESY__CACHE_BUILD_PATH: /Users/runner/.esy/3__________________________________________________________________/b
      ESY__CACHE_SOURCE_TARBALL_PATH: /Users/runner/.esy/source/i
      MACOSX_DEPLOYMENT_TARGET: 10.12
      CACHE_ARTIFACT_NAME: cache-$(Agent.OS)-install
    # ESY__NPM_ROOT: /usr/local/lib/node_modules/esy

    steps:
       - run: |
          npm install -g rimraf
          brew cleanup
          brew update-reset
          brew install ragel
          ls /Applications/Xcode*
          xcodebuild -version
          npm install -g node-gyp
          node-gyp list
          node-gyp install 14.15.4
          node-gyp list
          node install-node-deps.js --prod	
          npm install -g esy@0.6.7
          npm install -g yarn
          npm install -g prettier
          prettier --check **/*.js
          git diff --exit-code
          esy install
          esy clean-extensions
          git diff --exit-code
          esy @bench install
          git diff --exit-code
          esy @test install
          git diff --exit-code
          esy @integrationtest install
          git diff --exit-code
          esy bootstrap
          esy build
          esy format
          git diff --exit-code
          esy lint
          yarn audit
          npm install
          npm run build
          esy @release install
          esy @release build
